src/JavaScript.Workshop/JavaScript.Workshop/Areas/Ajax/Controllers/TocController.cs
using System.Web.Mvc;

namespace JavaScript.Workshop.Areas.Ajax.Controllers
{
    public class TocController : Controller
    {
        //
        // GET: /AdvancedJavascript/Toc/

        public ActionResult Index()
        {
            return View();
        }

    }
}

src/JavaScript.Workshop/JavaScript.Workshop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JavaScript.Workshop.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

src/JavaScript.Workshop/JavaScript.Workshop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<p>
    This workshop is composed by <a href="http://marcofranssen.nl">Marco Franssen</a>, Jan Saris and <a href="http://sandervandevelde.wordpress.com/">Sander van de Velde</a>.
</p>

src/JavaScript.Workshop/JavaScript.Workshop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Javascript Workshop";
}

<h2>Table of Contents</h2>
<ul>
    <li>@Html.ActionLink("Basic JavaScript", "Index", "Toc", new { area = "BasicJavaScript" }, null)</li>
    <li>@Html.ActionLink("Ajax", "Index", "Toc", new { area = "Ajax" }, null)</li>
    <li>@Html.ActionLink("JQuery UI", "Index", "Toc", new { area = "JQueryUI" }, null)</li>
    <li>@Html.ActionLink("Advanced JavaScript", "Index", "Toc", new { area = "AdvancedJavascript" }, null)</li>
    <li>@Html.ActionLink("Knockout JS", "Index", "Toc", new { area = "KnockoutJS" }, null)</li>
</ul>